### ISSUE TITLE
URL must be manually entered to localhost for dev server

### ISSUE THREAD

**Issue by dtgay** [FOSSRIT/charsheet#30]
Pyramid doesn't want to link you to localhost when starting the dev server, which is where you must be for the GitHub login redirection to work. You will be sent to 127..., which does not work. Altering the setting in development.ini did not seem to have any effect.

**Comment by Qalthos** [comment]
Changing the URL from localhost to 127.0.0.1 in the Github application settings seems to have done the trick. Reopen if troublesome.
