### ISSUE TITLE
Handle missing DB tables

### ISSUE THREAD

**Issue by dtgay** [FOSSRIT/charsheet#32]
Showing global stats and searching for a handle both needed cases where the necessary DB tables had not been initialized yet (in the case a charsheet has never been generated). I covered the global stats, but there still needs to be an alert message for handle searching.

**Comment by Qalthos** [comment]
Not sure what you mean. SQLAlchemy initializes the DB at start, and nothing should fail catastrophically, so #31 should be sufficient, unless I'm missing sometthing.

**Comment by dtgay** [comment]
Hmm, this is one of those scenarios where I'm not quite sure where I was at when I opened this ticket. I think you're right, and that the opening of this ticket was caused by a mix of:
1. Things that have since been resolved
2. My lack of understanding of Pyramid, which has been since improved

I'll close this. We can always re-open it if it turns out that it is still relevant.
