### ISSUE TITLE
Give people a class

### ISSUE THREAD

**Issue by Qalthos** [FOSSRIT/charsheet#35]
I'd like to take the top two skills of a user together to give them a class to further individualize sheets.

These ideas are just a starting point, to be actively debated if you think they're wrong and not to be taken as gospel.

Unsure if complements or replaces #28.

STR WIS     Battlemage
STR DET     Barbarian
STR DEX     Monk
STR LED     Paladin
STR POP     Knight
WIS DET     Wizard
WIS DEX     Sorcerer
WIS LED     Cleric
WIS POP     Bard
DET DEX     Ranger
DET LED    Meister
DET POP     Tourist
DEX LED    Druid
DEX POP     Rogue
LED POP    Heirophant

**Comment by dtgay** [comment]
This is awesome. We should sit down and go over each combo and write a single line explaining why we chose what stats for each class.

As for #28, I think this replaces the "job name" part, but doesn't resolve the fact that #28 suggests that the **chosen** class gives goals. With this commit, your class is assigned to you, which I actually like better... Hmm. I will close #28 as wontfix and maybe open a new one for goals.

Thanks, @Qalthos!

**Comment by Qalthos** [comment]
Thanks to @mansam for the following:

DET LED    Meister
DEX LED    Druid
LED POP    Heirophant

**Comment by Qalthos** [comment]
Ooops, forgot to tag this. I implemented this in b929b9a0b4c8c3576527b61ff78a9d0ec3afc262
